name: Deploy to UpCloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Sync files to UpCloud
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Syncing all files except for node_modules and including the test file
          sshpass -p "$SSH_PASSWORD" rsync -avz --delete --exclude='node_modules' --include='test/example.test.js' ./ satyam@95.111.219.120:~/Studio04
